### ISSUE TITLE
Suggestion: use gradle-incap-helper to generate META-INF file for Gradle incremental annotation processing 

### ISSUE THREAD

**Issue by tbroyer** [mikewacker/annotation-processor-example#32]
See https://github.com/tbroyer/gradle-incap-helper
This is basically the auto-service of incremental processing.

**Comment by mikewacker** [comment]
Done.

One nuance: I also had to add `testCompileOnly 'net.ltgt.gradle.incap:incap'`, else I would get this error:
```
> Task :immutable-processor:compileTestJava FAILED
warning: unknown enum constant IncrementalAnnotationProcessorType.ISOLATING
  reason: class file for net.ltgt.gradle.incap.IncrementalAnnotationProcessorType not found
warning: unknown enum constant IncrementalAnnotationProcessorType.ISOLATING
  reason: class file for net.ltgt.gradle.incap.IncrementalAnnotationProcessorType not found
error: warnings found and -Werror specified
1 error
2 warnings
```

**Comment by tbroyer** [comment]
Ah, right, I'll update the readme.
One possibility would be `compileOnlyApi` but it adds the dependency as `<scope>compile</scope>` in the POM; that's probably small enough to be negligible.
